---
- name: Setup Zellij Config Directory
  file:
    path: "{{ zellij_config_dir }}"
    state: directory
    mode: '0755'

- name: Zellij | Copies Zellij Config | template
  template:
    src: zellij/config.yaml.j2
    dest: "{{ zellij_config_file }}"

- name: Setup Zellij Layout Directory
  file:
    path: "{{ zellij_layout_dir }}"
    state: directory
    mode: '0755'

- name: Zellij | Copies Zellij Layout Configs | template
  template:
    src: '{{ item.src }}'
    dest: "{{ zellij_layout_dir }}/{{ item.path  | regex_replace('\\.j2$', '') }}"
  with_filetree: '../templates/zellij/layouts'
  when: item.state == 'file'
