---
- name: Bash | Copies .bashrc | template
  template:
    src: bash/bashrc.j2
    dest: "{{ dotfiles_user_home }}/.bashrc"

- name: Bash | Setup Bash Plugins Directory | directory
  file:
    path: "{{ bash_plugins }}"
    state: directory
    mode: '0755'

- name: Bash | Install FZF-Tab Plugin | git
  git:
    repo: "https://github.com/lincheney/fzf-tab-completion"
    dest: "{{ bash_fzf_tab }}"

- name: Bash | Install Git Fuzzy Plugin | git
  git:
    repo: "https://github.com/bigH/git-fuzzy"
    dest: "{{ bash_git_fuzzy }}"
